AWS_ACCESS_KEY_ID?=AKIAIJFOFDW37CJGLFCQ
AWS_IAM_USER=dotbc-queue
AWS_SECRET_ACCESS_KEY?=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
DEBUG?=dotbc*
NODE_ENV?=development

run: start

start: 
	NODE_ENV=$(NODE_ENV) \
	AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) \
	AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) \
	npm run dev;

.PHONY: test
