AWS_ACCESS_KEY_ID?="$(DOTBC_AWS_ACCESS_KEY_ID)"
AWS_BUCKET?="$(DOTBC_AWS_BUCKET)"
AWS_IAM_USER=dotbc-queue
AWS_SECRET_ACCESS_KEY?="$(DOTBC_AWS_SECRET_ACCESS_KEY)"
DEBUG?=site:*
NODE_ENV?=development

run: start

start: 
	DEBUG=$(DEBUG) \
	NODE_ENV=$(NODE_ENV) \
	AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) \
	AWS_BUCKET=$(AWS_BUCKET) \
	AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) \
	npm run dev;

.PHONY: test
