import React, { Component, PropTypes } from 'react'
import { Field, reduxForm } from 'redux-form';

export default class LegalInfo extends Component {

  render() {
    
    const { handleSubmit } = this.props;
    return (
      <section id="legalInfo">
        <label>DOTBC UPLOADER TERMS AND CONDITIONS</label>
        <div id="legalBlock">
          <p>These terms and conditions (this “Agreement”) by and between Dot Blockchain Music, Inc. (“DotBC” or “We”) and you (“You”) govern provision of the DotBC beta testing uploader service (the “Service”), and is effective as of the moment You (a) utilize the Service or (b) establish an account with DotBC using DotBC’s registration service. DotBC may revise this Agreement from time to time by posting a new version hereof on the DotBC Website. Your continued use of the Service constitutes acceptance of such revisions to this Agreement.</p>
          <p>1. The Service includes the DotBC uploader tool which allows You to upload rights ownership data and information into the DotBC system for referencing and logging into a blockchain test environment.</p>
          <p>2. This Agreement will continue until terminated by either party. Your continued use of the Service indicates Your continued acceptance of this Agreement. DotBC may restrict or discontinue your access to the Service at any time for any reason.</p>
          <p>3.	You warrant that You will not, using the Service to: (i) perpetrate any security breach, network attack, act of hacking, or distribution of any virus, worm, or other harmful code; (ii) perpetrate any fraud or intellectual property infringement; (iii) disseminate or post any material or information that is or may be threatening, libelous, obscene, harassing, offensive or knowingly false; (iv) threaten or harass any DotBC employee, agent, or representative by telephone, in person, or through any other means of communication; (v) perpetrate any crime or other illegal activity; (vi) tamper with other DotBC accounts, commit unauthorized intrusion into any part of DotBC’s system; (vii) scan or scrape any data in the Service;</p>
          <p>4. DotBC has no obligation to monitor the Service but may do so and may disclose information regarding use of the Service for any reason, including: to satisfy laws, regulations, or governmental, legal, or law-enforcement requests; to operate the Service properly; or to protect itself and its customers. DotBC will use all commercially reasonable efforts to protect Your data from dissemination to third parties during the testing phase, and We will provide you at least ten (10) business days prior written notification if the Service will be put into a live environment.</p>
          <p>5.	The Service provided by DotBC is licensed to You and remains DotBC’s sole and exclusive property, unless otherwise covered and licensed under an open source license. You retain ownership of all of Your data uploaded through the Service, but You hereby grant to DotBC and its approved third party suppliers, partners, and other customers a revocable, no-charge license to use Your data solely for testing of the Service and DotBC’s rights ownership reconciliation services.</p>
          <p>6.	DotBC may interrupt the Service to perform maintenance. You are responsible for maintaining security, for maintaining patches and disaster recovery systems, and for maintaining backups. DotBC will not be liable for loss of data or for breaches in system integrity. You agree to promptly report any Service failures to DotBC.</p>
          <p>7.	 Disclaimers and Warranties.</p>
          <p>(a) THE SERVICE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. DOTBC DOES NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE FROM VIRUSES OR OTHER HARMFUL COMPONENTS. DOTBC MAKES NO EXPRESS OR IMPLIED WARRANTIES WHATSOEVER, INCLUDING WITHOUT LIMITATION, WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE. </p>
          <p>(b) DOTBC WILL NOT BE LIABLE FOR ANY CONSEQUENTIAL, INCIDENTAL, EXEMPLARY, PUNITIVE, OR MULTIPLE DAMAGES, EVEN IF DOTBC WAS ADVISED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES. DOTBC’S MAXIMUM LIABILITY ARISING OUT OF OR RELATED TO THIS AGREEMENT OR THE SERVICE WILL NOT EXCEED FIVE HUNDRED DOLLARS ($500).</p>
          <p>(c) DOTBC WILL HAVE NO LIABILITY WHATSOEVER FOR ANY CLAIMS, LOSSES, ACTIONS, DAMAGES, SUITS, OR PROCEEDINGS RESULTING FROM: (i) THIRD PARTIES ACCESSING YOUR DATA OR ASSIGNED COMPUTERS; (ii) SECURITY BREACHES; (iii) EAVESDROPPING; (iv) DENIAL OF SERVICE ATTACKS; (v) INTERCEPTION OF TRAFFIC SENT OR RECEIVED USING THE EQUIPMENT OR SERVICE; (vi) YOUR RELIANCE ON OR USE OF THE SERVICE; (vii) MISTAKES, OMISSIONS, INTERRUPTIONS, DELETIONS OF FILES, ERRORS, DEFECTS, DELAYS IN OPERATION, OR OTHER FAILURES OF PERFORMANCE OF THE EQUIPMENT OR SERVICE; (viii) THE ACCURACY, COMPLETENESS, AND USEFULNESS OF THE SERVICE; OR (ix) LOSS OF DATA OR LOSS OF ACCESS TO DATA.</p>
          <p>(d) DOTBC’S LIMITATIONS AND EXCLUSIONS OF LIABILITY SET FORTH IN THIS SECTION AND IN THIS AGREEMENT APPLY EQUALLY TO DOTBC’S OFFICERS, EMPLOYEES, AGENTS, CONTRACTORS, REPRESENTATIVES, SUPPLIERS, SUBSIDIARIES, PARENTS, AND AFFILIATED COMPANIES.</p>
          <p>(e) YOU WARRANT THAT YOU HAVE THE RIGHT AND AUTHORITY TO UPLOAD YOUR INFORMATION TO THE SERVICE AND THAT, TO THE BEST OF YOUR KNOWLEDGE, THE DATA YOU UPLOAD AND ENTER INTO THE SERVICE IS CORRECT.</p>
          <p>9. Miscellaneous. This Agreement will be construed in accordance with and governed by the laws of the State of New York without giving effect to any choice of law rules. The parties hereby consent to the personal and exclusive jurisdiction and venue of the federal and state courts of New York, New York. No delay, failure, or waiver of either party’s exercise or partial exercise of any right or remedy under this Agreement will operate to limit, impair, preclude, cancel, waive, or otherwise affect such right or remedy. If any provision of this Agreement is held invalid, illegal, or unenforceable, the validity, legality, or enforceability of the remaining provisions will in no way be affected or impaired thereby. This Agreement, with any other instrument or document referenced herein, which are incorporated by reference as though set forth herein, embodies the final, full, and exclusive statement of the agreement between the parties, and as of its date supersedes all prior agreements, negotiations, representations, and proposals, written or oral, relating to the subject-matter hereof. All written communications to You will be deemed delivered if sent to the contact information provided to Your address given at registration, unless You provide alternate contact information in writing. All written communications to DotBC shall be mailed to Dot Blockchain Music, Inc., 99 Gold Street Suite 1C, Brooklyn, NY 11201.</p>
        </div>
      </section>
    );

  }

};